services:
  frontend:
    image: gautamkaran/voisafe-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ${VITE_API_URL:-/api}
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: gautamkaran/voisafe-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://db/voisafe"
      JWT_SECRET: "your_jwt_secret_key"
      JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"
      SUPER_ADMIN_EMAIL: "admin@voisafe.org"
      SUPER_ADMIN: "admin123"
      FRONTEND_URL: "http://frontend:5173"

  db:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}
