services:
  mongo:
    image: mongo:7
    container_name: voisafe-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: voisafe-backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      DB_URI: mongodb://mongo:27017/voisafe
      PORT: 3000
      JWT_SECRET: "your_jwt_secret_key"
      JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"

    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000/api
    container_name: voisafe-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mongo_data:
