services:
  caddy:
    image: caddy:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: >
      sh -c 'printf "voisafe.gautamkaran.cloud {\n  reverse_proxy frontend:4173\n}\napi.gautamkaran.cloud {\n  reverse_proxy backend:3001\n}\n" > /etc/caddy/Caddyfile && caddy run --config /etc/caddy/Caddyfile'
    restart: unless-stopped

  frontend:
    image: gautamkaran/voisafe-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: gautamkaran/voisafe-backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      MONGO_URI: "mongodb://db/voisafe"
      JWT_SECRET: "your_jwt_secret_key"
      JWT_REFRESH_SECRET: "your_jwt_refresh_secret_key"
      SUPER_ADMIN_EMAIL: "admin@voisafe.org"
      SUPER_ADMIN: "admin123"

  db:
    image: mongo:7
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  caddy_data:
  caddy_config:
  mongo_data: {}
